"""PR 发布层（W4）：把执行链的产物变成一个可 review 的 Pull Request。

PR body 由**服务层结构化拼装**（告警摘要 / 根因分析 / 修复说明 / 测试证据 /
审计记录），原料来自 job 记录与执行证据——不让 LLM 自由发挥 body，review 者
不看 agent 日志也能做判断（架构文档决策 3）。

这里没有任何 merge 能力：合并永远是人做的事（W4 安全红线）。
"""

from __future__ import annotations

import logging
import re
from typing import Any

from mewcode.config import ServiceConfig

from .execution import COMMIT_EXCLUDES, ExecutionContext, PublishResult
from .jobs import Job, JobStore
from .sop import extract_logs, render_alert_context
from .vcs import CheckStatus, VCSError, VCSProvider

log = logging.getLogger(__name__)

_REPORT_KEYS = r"(?:ROOT CAUSE|FIX|VERIFICATION|SELF\-CHECK)"
#: 报告标题的常见装饰：agent 天然会写成 `**FIX:**` / `### ROOT CAUSE:` / `> FIX:`。
#: 只认行首裸标题的话，加粗写法会导致整段被静默丢掉——真机踩到过：
#: `**SELF-CHECK:**` 没被识别，规范自查（M2 验收标准 2 的证据）没进 PR body。
_HEADING = rf"^[#>*_`\s]*({_REPORT_KEYS})[*_`\s]*:[*_`\s]*"
_SECTION_RE = re.compile(
    _HEADING + r"(?P<body>.*?)" + rf"(?=^{_HEADING}|\Z)",
    re.IGNORECASE | re.MULTILINE | re.DOTALL,
)

#: 进 PR body 审计表的事件类型：只保留状态推进与验证证据。
#: agent_prompt / agent_tool_use / agent_usage 属于运行细节，会把 review 者
#: 淹没在噪音里（PR body 的目标是"不看 agent 日志也能做判断"）。
AUDIT_TIMELINE_KINDS = frozenset({
    "worktree_ready", "baseline_tests", "verify_tests", "test_delta",
    "agent_finished", "transition", "verification_retry", "ci_status",
    "ci_retry", "pr_created", "pr_updated", "escalated", "deduped",
    # 集成验证（M2 W4）：起依赖 / 跑集成测试 / 清理各是一条证据
    "integration_up", "integration_tests", "integration_down", "integration_skipped",
})


def filter_timeline(timeline: list[tuple[str, str, str]]) -> list[tuple[str, str, str]]:
    """从完整审计（ts, kind, detail）里筛出适合放进 PR body 的条目。"""
    return [entry for entry in timeline if entry[1] in AUDIT_TIMELINE_KINDS]


def parse_agent_report(text: str) -> dict[str, str]:
    """从 agent 的收尾报告里抽 ROOT CAUSE / FIX / VERIFICATION 三段。

    抽不到就退化为"把全文当根因分析"——宁可多给原文，也不要凭空编一段。
    """
    sections: dict[str, str] = {}
    for match in _SECTION_RE.finditer(text or ""):
        sections[match.group(1).upper()] = match.group("body").strip()
    return sections


def build_pr_title(job: Job) -> str:
    title = (job.title or job.payload.get("alertname") or "alert").strip()
    title = re.sub(r"\s+", " ", title)[:120]
    return f"[MewCode] {title}"


def _integration_section(integration: Any | None) -> list[str]:
    """集成验证（M2 W4）的证据小节：起依赖 → 跑集成测试 → 清理。

    ``None``（仓库没有 compose 文件）不产生小节；``skipped`` 如实写明原因——
    "没做"和"做了没过"对 review 者是两回事。
    """
    if integration is None:
        return []
    lines = ["", "## 集成验证（自起测试环境）", ""]
    if not integration.ran:
        lines += [
            f"- Compose 文件：`{integration.compose_file}`",
            f"- ⏭️ 未执行：{integration.skipped}",
            "",
            "> 单测证据仍然有效；集成验证需要容器运行时，本环境不具备。",
        ]
        return lines

    lines.append(f"- Compose 文件：`{integration.compose_file}`（project `{integration.project}`）")
    verdict = "✅ 启动成功" if integration.up_ok else "❌ 启动失败"
    lines.append(f"- 依赖环境：`docker compose up -d --wait` {verdict}")
    if integration.up_ok and integration.test is not None:
        test = integration.test
        result = "✅ 通过" if test.passed else "❌ 失败"
        lines.append(f"- 集成测试：`{test.command}` → {result}（exit {test.exit_code}）")
    elif integration.up_ok:
        lines.append("- 集成测试：未执行")
    lines.append("")
    lines.append("> 集成测试在沙箱容器内执行，经 compose 网络按服务名访问依赖；任务结束已 `down -v` 清理。")

    if not integration.up_ok and integration.up_output:
        lines += [
            "", "<details><summary>依赖环境启动输出</summary>", "", "```",
            integration.up_output[-2000:], "```", "", "</details>",
        ]
    if integration.services.strip():
        lines += [
            "", "<details><summary>依赖服务状态（docker compose ps）</summary>", "", "```",
            integration.services.strip()[-2000:], "```", "", "</details>",
        ]
    if integration.test is not None and integration.test.output:
        lines += [
            "", "<details><summary>集成测试输出</summary>", "", "```",
            integration.test.output[-2000:], "```", "", "</details>",
        ]
    if integration.down_output.strip():
        lines += [
            "", "<details><summary>环境清理（docker compose down -v）</summary>", "", "```",
            integration.down_output.strip()[-1000:], "```", "", "</details>",
        ]
    return lines


def build_pr_body(
    job: Job,
    context: ExecutionContext,
    timeline: list[tuple[str, str, str]],
    mcp_servers: list[str] | None = None,
) -> str:
    """拼装 PR body（结构化模板，见 W4.2）。"""
    report = parse_agent_report(context.agent.final_text)
    root_cause = report.get("ROOT CAUSE") or (context.agent.final_text or "").strip() or "(agent 未给出结论)"
    fix_note = report.get("FIX") or "(见改动内容)"
    verification = report.get("VERIFICATION") or ""

    lines: list[str] = [
        "<!-- generated by MewCode service: alert-driven autofix -->",
        "## 告警摘要",
        "",
        render_alert_context(job),
        "",
        f"- Job: `{job.id}`",
        f"- Fingerprint: `{job.fingerprint or 'n/a'}`",
    ]
    evidence = extract_logs(job)
    if evidence:
        lines += [
            "", "<details><summary>告警证据（日志 / 注解）</summary>", "",
            "```", evidence, "```", "", "</details>",
        ]

    lines += [
        "",
        "## 根因分析",
        "",
        root_cause,
        "",
        "## 修复说明",
        "",
        fix_note,
        "",
        f"改动规模：{context.diff_stat()}",
        "",
    ]
    if context.changed_files:
        lines += [f"- `{path}`" for path in context.changed_files[:30]]
        if len(context.changed_files) > 30:
            lines.append(f"- … 其余 {len(context.changed_files) - 30} 个文件")

    lines += ["", "## 测试证据", "", "| 阶段 | 命令 | 结果 |", "|---|---|---|"]
    def _row(label: str, outcome) -> str:
        if outcome is None:
            return f"| {label} | (未配置 test_command) | — |"
        verdict = "✅ 通过" if outcome.passed else "❌ 失败"
        return f"| {label} | `{outcome.command}` | {verdict}（exit {outcome.exit_code}） |"

    lines.append(_row("修复前", context.baseline_test))
    lines.append(_row("修复后", context.verify_test))
    if verification:
        lines += ["", f"agent 自述的验证过程：{verification}"]

    self_check = report.get("SELF-CHECK")
    if self_check:
        lines += [
            "",
            "## 规范自查（org-code-style）",
            "",
            self_check,
            "",
            "> 自查由 agent 完成、未经过人工核对；review 时请重点看未满足项。",
        ]
    if context.baseline_test is not None and context.baseline_test.output:
        lines += [
            "", "<details><summary>修复前测试输出</summary>", "", "```",
            context.baseline_test.output[-2000:], "```", "", "</details>",
        ]
    if context.verify_test is not None and context.verify_test.output:
        lines += [
            "", "<details><summary>修复后测试输出</summary>", "", "```",
            context.verify_test.output[-2000:], "```", "", "</details>",
        ]

    lines += _integration_section(context.integration)

    configured_mcp = [name for name in (mcp_servers or []) if name]
    if configured_mcp or context.agent.mcp_tool_calls:
        lines += ["", "## 内部工具链（只读 MCP）", ""]
        if configured_mcp:
            lines.append("- 已配置：" + ", ".join(f"`{name}`" for name in configured_mcp))
        if context.agent.mcp_tool_calls:
            used = ", ".join(f"`{name}`" for name in context.agent.mcp_tools_used)
            lines.append(f"- 本次使用：{context.agent.mcp_tool_calls} 次调用（{used}）")
        else:
            lines.append("- 本次使用：未使用（告警证据已足够定位问题）")
        lines.append("")
        lines.append("> 内部工具均声明只读（MCP readOnlyHint）：可查询，不可修改外部系统。")

    lines += ["", "## 审计记录", "", f"- 修复尝试次数：{context.attempts}", ""]
    entries = filter_timeline(timeline)
    if entries:
        lines += ["| 时间 | 事件 |", "|---|---|"]
        for ts, kind, detail in entries[-25:]:
            lines.append(f"| {ts} | `{kind}` {detail.replace('|', '/')[:250]} |")

    lines += [
        "",
        "---",
        "",
        "> 本 PR 由 MewCode 服务在无人干预下生成（告警 → 修复 → 测试 → PR）。",
        "> 合并前请人工 review：服务没有任何 merge 权限。",
    ]
    return "\n".join(lines)


class PullRequestPublisher:
    """实现 ExecutionChain 的 Publisher 契约（branch → commit → push → PR）。"""

    def __init__(self, vcs: VCSProvider, store: JobStore, config: ServiceConfig) -> None:
        self.vcs = vcs
        self.store = store
        self.config = config

    async def publish(self, job: Job, context: ExecutionContext) -> PublishResult:
        branch = f"mewfix/{job.id}"
        await self.vcs.ensure_branch(context.work_dir, branch)
        message = (
            f"{build_pr_title(job)}\n\n"
            f"Alert-driven fix for {job.repo} (job {job.id}).\n"
            f"Attempts: {context.attempts}; diff: {context.diff_stat()}.\n"
        )
        committed = await self.vcs.commit_all(context.work_dir, message, exclude=COMMIT_EXCLUDES)
        if not committed:
            raise VCSError("nothing to commit: worktree has no staged changes")
        await self.vcs.push(context.work_dir, branch)

        slug = await self.vcs.resolve_repo_slug(context.work_dir)
        timeline = [(e.ts, e.kind, e.detail) for e in await self.store.events(job.id)]
        body = build_pr_body(
            job, context, timeline, mcp_servers=[cfg.name for cfg in self.config.mcp_servers]
        )

        existing = await self.vcs.find_open_pr(slug, branch)
        if existing is not None:
            # 重试路径：PR 已存在，刷新 body 而不是重复开单
            await self.vcs.update_pr_body(slug, existing.number, body)
            info = existing
            events = [("pr_updated", f"PR #{existing.number} refreshed after retry: {existing.url}")]
        else:
            info = await self.vcs.create_pr(slug, branch, build_pr_title(job), body)
            events = [("pr_created", f"PR #{info.number} at {info.url} (base={info.base_branch})")]

        return PublishResult(pr_url=info.url, branch=branch, extra_events=events)


class GitHubCIGate:
    """CI 门禁：等 checks 出结论；超时（pending）由执行链 escalate，不假装成功。"""

    def __init__(self, vcs: Any) -> None:
        self.vcs = vcs

    async def wait(
        self, job: Job, context: ExecutionContext, published: PublishResult
    ) -> CheckStatus:
        slug = await self.vcs.resolve_repo_slug(context.work_dir)
        sha = await self.vcs.head_sha(context.work_dir)
        return await self.vcs.poll_checks(slug, sha)
